"""Added stream enum2

Revision ID: 3c41204cf2c5
Revises: 8307d7a29cf0
Create Date: 2023-01-25 10:49:00.822402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3c41204cf2c5"
down_revision = "8307d7a29cf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student",
        sa.Column(
            "stream_enum",
            sa.Enum("Commerce", "Science", "Arts", name="streamenum"),
            nullable=True,
        ),
    )
    op.drop_column("student", "stream")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student", sa.Column("stream", mysql.VARCHAR(length=20), nullable=True)
    )
    op.drop_column("student", "stream_enum")
    # ### end Alembic commands ###
