"""Added stream enum

Revision ID: 8307d7a29cf0
Revises: 7a27c90fa5a0
Create Date: 2023-01-25 10:45:42.965834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8307d7a29cf0"
down_revision = "7a27c90fa5a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
