"""changed stream_enum column to streams

Revision ID: ccbf23a4ec4b
Revises: 0cab1f253fae
Create Date: 2023-01-25 10:51:50.204452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccbf23a4ec4b"
down_revision = "0cab1f253fae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
